version: "3"

services:
  frontend:
    image: node:14
    volumes:
      - ./frontend:/home/mediacms.io/mediacms/frontend/
    working_dir: /home/mediacms.io/mediacms/frontend/
    command: bash -c "npm install && npm run start"
    env_file:
      - ./frontend/.env
    ports:
      - "8088:8088"
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    image: mediacms/mediacms-dev:latest
    ports:
      - "80:80"
    volumes:
      - ./:/home/mediacms.io/mediacms/
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  selenium_hub:
    container_name: selenium_hub
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  selenium_firefox:
    image: selenium/node-firefox-debug
    shm_size: 2gb
    depends_on:
      - selenium_hub
    ports:
      - "5900:5900"
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  db:
    image: postgres:13
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediacms"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
